### ISSUE TITLE
Bug - Crash with latest SE Version Update 198 - Warfare 1: Field Engineer

### ISSUE THREAD

**Issue by kontu** [sirhamsteralot/HaE-PBLimiter#37]
Game version: Game Version: 1.198.24

PBlimiter: 'HaE PBLimiter' (v1.1.1.1)

18:33:06.5719 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Boolean Sandbox.Game.Entities.Cube.MySlimBlock.DoDamage(Single, VRage.Utils.MyStringHash, Boolean, System.Nullable`1<VRage.Game.ModAPI.MyHitInfo>, Int64)'.
   at HaE_PBLimiter.PBTracker.<>c__DisplayClass25_0.<DamagePB>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\Users\Administrator\Desktop\Personal Projects\torch\Torch\VRageGame.cs:line 296
   at Torch.VRageGame.Run() in C:\Users\Administrator\Desktop\Personal Projects\torch\Torch\VRageGame.cs:line 130
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

I didn't actually see this crash on startup, I was up and running for a bit before it took the server down (I *think* a pb needed punishing? I'm not sure)

**Comment by sirhamsteralot** [comment]
Pushed update to torch.net, should be fixed now, let me know if it isn
